### ISSUE TITLE
Actividad de calculadora

### ISSUE THREAD

**Issue by karencfv** [gtfmx/intro-go#1]
Refinar el texto del README y código. No estaría mal poner multiplicación y división, o ponerlo como un reto extra para que las niñas hagan sus propias funciones 🤔

**Comment by J3551c9** [comment]
Suena genial el retro extra!!!

**Comment by karencfv** [comment]
Resuelto con https://github.com/gtfmx/intro-go/commit/ccda63373351a0663f1769d395e65cc315efc30a
